version: '2.1'

orbs:
  python: circleci/python@2.0.3
  aws-ecr: circleci/aws-ecr@7.3.0

jobs:
  check-branch:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Check selected branch and current branch
          command: |
            if [[ "$CIRCLE_BRANCH" == *base-branch* && "$CIRCLE_PULL_REQUEST_BASE_BRANCH" == "base" ]]; then
              echo "Selected branch is base and current branch has base-branch in its name"
            else
              echo "Selected branch is not base or current branch does not have base-branch in its name..!!!"
              exit 1
            fi
  linting:
    executor: python/default
    resource_class: small
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements-app.txt
      - run:
          name: Lint with Black and isort
          command: |
            black --check --diff .
            isort --check-only --diff --profile black --line-length 80 .
      - run:
          name: Lint with Flake8
          command: flake8 .
  testing:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install pytest
      - run:
          name: Test with Pytest
          command: pytest -sv


  
workflows:
  main:
    jobs:
      - check-branch:
          context: CICD
          filters:
            branches:
              only: /.*base-branch/
            tags:
              only: /.*/
      - linting:
          filters:
            tags:
              only: /.*master-branch*/
            branches:
              only: /.*master-branch/
      - testing:
          filters:
            tags:
              only: /.*master-branch*/
            branches:
              only: /.*master-branch-tests/
