version: '2.1'

orbs:
  python: circleci/python@2.0.3
  aws-ecr: circleci/aws-ecr@7.3.0

jobs:
  linting:
    executor: python/default
    resource_class: small
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements-app.txt
      - run:
          name: Lint with Black and isort
          command: |
            black --check --diff .
            isort --check-only --diff --profile black --line-length 80 .
      - run:
          name: Lint with Flake8
          command: flake8 .
  testing:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install pytest
      - run:
          name: Test with Pytest
          command: pytest -sv


  
workflows:
  main:
    jobs:
      - linting:
          filters:
            tags:
              only: /.*master-branch*/
            branches:
              only:
                - master
      - testing:
          filters:
            tags:
              only: /.*master-branch*/
            branches:
              only: /.*master-branch-tests/

