version: '2.1'

orbs:
  python: circleci/python@2.0.3
  aws-ecr: circleci/aws-ecr@7.3.0

jobs:
  check-branch:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Check selected branch and current branch
          command: |
            if [[ $CIRCLE_BRANCH == *base-branch* && $BASE_BRANCH == "base" ]]; then
              echo "Selected branch is base and current branch has base-branch in its name" $CIRCLE_BRANCH "///" $BASE_BRANCH "///" $CIRCLE_PULL_REQUEST "///" $CIRCLE_PULL_REQUEST_TARGET_BRANCH
            else
              echo "Selected branch is not base or current branch does not have base-branch in its name..!!!" $CIRCLE_BRANCH "///" $BASE_BRANCH "///" $CIRCLE_PULL_REQUEST "///" $CIRCLE_PULL_REQUEST_TARGET_BRANCH
              exit 1
            fi
  linting:
    executor: python/default
    resource_class: small
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r build/requirements-base.txt
      - run:
          name: Lint with Black and isort
          command: |
            black --check --diff .
            isort --check-only --diff --profile black --line-length 80 .
      - run:
          name: Lint with Flake8
          command: flake8 .
  testing:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install pytest
      - run:
          name: Test with Pytest
          command: pytest -sv


workflows:
  uplift-app:
    jobs:
      - check-branch:
          context: CICD
          filters:
            branches:
              only: /.*base-branch/
            tags:
              only: /.*/
      - linting:
          context: CICD
          filters:
            branches:
              only: /.*base-branch/
            tags:
              only: /.*/
      - testing:
          context: CICD
          filters:
            branches:
              only: /.*base-branch/
            tags:
              only: /.*/
