name: Merge PR to branch

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch to merge into
        run: |
          if [[ $PR_BRANCH_NAME == /*base-branch && $BASE_BRANCH_NAME != "base" ]]; then
            echo "error: Base branches can only be merged into the base branch.!!!!"
            exit 1
          fi
 
