name: Merge PR to branch

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch to merge into
        run: |
          if [ $PR_BRANCH_NAME == /*base-branch && ${{ github.base_ref }} != "base" ]; then
            echo "error: Base branches can only be merged into the base branch.!!!!" "///" $PR_BRANCH_NAME "///" ${{ github.base_ref }} "///"
            exit 1
          else
            echo "OK: Base branches is base branch.!!!!" "///" $PR_BRANCH_NAME "///" ${{ github.base_ref }} "///"
            exit 1
          fi
 
