name: Merge PR to branch

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch to merge into
        run: |
          if [ ${{ github.base_ref }} != "base" ]; then
            echo "error: Base branches can only be merged into the base branch.!!!!" "///" ${{ github.base_ref }} "///"
            exit 1
          else
            echo "OK: Base branches is base branch.!!!!" "///" ${{ github.base_ref }} "///"
          fi
      - name: Check if PR name contains 'base branch'
        run: |
          pr_title="${{ github.event.pull_request.title }}"
          if [[ ! $pr_title == *"base branch"* ]]; then
            echo "error: The pull request name must contain 'base branch'" "///" ${{ github.event.pull_request.title }} "///"
            exit 1
          else
            echo "OK: Branch name contains base branch.!!!!" "///" ${{ github.event.pull_request.title }} "///"
          fi
